name: Cross Compile and Release
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-gnu
            os: windows-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: aarch64-pc-windows-msvc
            os: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install target
        run: rustup target add ${{ matrix.target }}

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Rename output binary (Unix)
        if: runner.os != 'Windows'
        run: |
          mv target/${{ matrix.target }}/release/bankers_algorithm target/${{ matrix.target }}/release/bankers_algorithm-${{ matrix.target }}-${{ steps.date.outputs.date }}

      - name: Rename output binary (Windows)
        if: runner.os == 'Windows'
        run: |
          ren target\${{ matrix.target }}\release\bankers_algorithm.exe bankers_algorithm-${{ matrix.target }}-${{ steps.date.outputs.date }}.exe

      - name: List build outputs
        run: ls target/${{ matrix.target }}/release/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bankers_algorithm_demo_202211200227-${{ matrix.target }}-${{ steps.date.outputs.date }}
          path: target/${{ matrix.target }}/release/bankers_algorithm-${{ matrix.target }}-${{ steps.date.outputs.date }}