name: Cross Compile and Release
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-gnu
            os: windows-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: aarch64-pc-windows-msvc
            os: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install target
        run: rustup target add ${{ matrix.target }}

      - name: Get short commit hash (Unix)
        if: runner.os != 'Windows'
        id: short-sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Get short commit hash (Windows)
        if: runner.os == 'Windows'
        id: short-sha
        run: echo sha=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Rename output binary (Unix)
        if: runner.os != 'Windows'
        run: |
          mv target/${{ matrix.target }}/release/bankers_algorithm target/${{ matrix.target }}/release/bankers_algorithm-${{ matrix.target }}-${{ steps.short-sha.outputs.sha }}

      - name: Rename output binary (Windows)
        if: runner.os == 'Windows'
        run: |
          ren target\${{ matrix.target }}\release\bankers_algorithm.exe bankers_algorithm-${{ matrix.target }}-${{ steps.short-sha.outputs.sha }}.exe

      - name: List build outputs (Unix)
        if: runner.os != 'Windows'
        run: ls target/${{ matrix.target }}/release/

      - name: List build outputs (Windows)
        if: runner.os == 'Windows'
        run: dir target\${{ matrix.target }}\release\

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bankers_algorithm_demo_202211200227-${{ matrix.target }}-${{ steps.short-sha.outputs.sha }}
          path: target/${{ matrix.target }}/release/bankers_algorithm-${{ matrix.target }}-${{ steps.short-sha.outputs.sha }}${{ runner.os == 'Windows' && '.exe' || '' }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        
      - name: Get short commit hash
        id: short-sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.short-sha.outputs.sha }}
          name: Release ${{ steps.short-sha.outputs.sha }}
          body: |
            Automated release based on commit ${{ github.sha }}
          draft: false
          prerelease: false
          files: |
            **/*.txt
            **/bankers_algorithm-*
            **/*.exe